organization: xudongwu
token: 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

prefix:
  datasets: xudongwu/
  models:  xudongwu/
  evaluations:  xudongwu/

collections:
  datasets: xudongwu/sail
  models: xudongwu/sail
  evaluations: xudongwu/sail
